### ISSUE TITLE
Requiring querystring but it's not a dependency in package.json

### ISSUE THREAD

**Issue by parroit** [defunctzombie/node-url#10]
I'm producing a bundle using [pure-cjs](https://github.com/RReverser/pure-cjs), a bundle packager similar  to browserify, and I discover this issue. 
I solved my problem by manually requiring [querystring](https://github.com/Gozala/querystring) in my own package.json, but I think it would be best to directly declare your dependency as you do with `punycode`

**Comment by forresto** [comment]
fixed: https://github.com/defunctzombie/node-url/commit/e0a2765246299587ce8f82f5e871fa974c1d63ea
