### ISSUE TITLE
Uncaught SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by call-a3** [defunctzombie/node-url#11]
When serving a browserify build with strict mode enabled, (The entire build is prefixed with `"use strict";`) the browser (in my case chrome) throws the following error:

`Uncaught SyntaxError: Use of const in strict mode.` originating at _url.js:115_

**Comment by aearly** [comment]
Strict mode prevents the use of keywords as var names -- regardless of
whether JS actually uses those keywords....

I think it's a guard against future features added to the language, but it
is silly.

**Comment by muhammadusman112** [comment]
ok fine

**Comment by ljharb** [comment]
This error was a bug in older versions of v8, and thus Chrome/node. I don't see any `const` or `let` usage in the package anymore, and modern engines don't have this problem anyways.

Happy to reopen if this is still occurring.
