### ISSUE TITLE
Ship with browser version

### ISSUE THREAD

**Issue by cburgmer** [defunctzombie/node-url#28]
[inlineresources](https://www.npmjs.com/package/inlineresources) depends on the url module. I'd like to make it easy for people to use in the browser.

So far I've shipped an all-in-one bundle. That is tedious and requires me to re-publish when it comes to updates to url and other bundled dependencies (let's not think of security updates).

I'd like to 
1. add a built step which will provide a UMD wrapped lib
2. re-point the `"main": "./url.js"` entry to the UMD bundle.

This would give people the freedom to use whatever they like. AMD, browserify, or just plain old <script> tags.

Let me know what you think.

**Comment by ljharb** [comment]
CJS provides that freedom, as every build tool is capable of handling it as input. AMD and UMD are both obsolete formats, as is "plain old script tags".

**Comment by sgpinkus** [comment]
Pretty sure the `<script>` tag is not obsolete. I think the request is make it so the url package can be used from unpkg.com or cdn.jsdelivr.ner or what out of the box, as well as just from a server file without a build. I want this too. It's useful for prototyping.

**Comment by ljharb** [comment]
Not the tag, but putting something in it that’s not a bundle certainly is.

**Comment by sgpinkus** [comment]
Not sure what that means :). I think the issue is asking for a build / bundle you can put in the script tag like say, axios does -- https://github.com/axios/axios/blob/v1.x/dist/axios.min.js. Many projects do this.

**Comment by ljharb** [comment]
Right - but what I’m saying is that using those is archaic. The proper and modern solution is to bundle your entire application, including its dependencies, and put *that* in a script tag.

**Comment by sgpinkus** [comment]
Yep OK we are on the same page. We disagree on whether it's archaic or not. My stance is web build tool chains are about the suckiest thing that exist, if you can get away with not using one for some simple prototype app, or even in a simple prod app, why the heck not? Form memory this is how you load things in JSFiddle and other such tools - very useful for prototyping.

On more thought, maybe it's not worth it for url package though. Browser already has URL as standard.
