### ISSUE TITLE
The Principle of Least Astonishment is broken

### ISSUE THREAD

**Issue by rtodea** [defunctzombie/node-url#29]
Consider the following scenario:
```
const url = require("url");
const someUrl = 'http://google.com?first=this&second=that';
const urlModel = url.parse(someUrl, true);

// change the query params
delete urlModel.query.first;
urlModel.query.third='some';

console.log(urlModel.query);

// expect the new URL to have the query params changed
console.log(url.format(urlModel));
// expected: http://google.com/?second=that&third=some
// actual: http://google.com?first=this&second=that
```

Instead if I modify the `.search` everything works as expected
```
const url = require("url");
const someUrl = 'http://google.com?first=this&second=that';
const urlModel = url.parse(someUrl, true);

// change the search string

urlModel.search = 'second=that&third=some';

// expect the new URL to have the query params changed
console.log(url.format(urlModel));
// http://google.com/?second=that&third=some
```

I have not found this behavior documented and I think it breaks [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

We have 2 options:

1. document this
2. change the behavior

**Comment by lanre-ade** [comment]
👍

**Comment by sheepsteak** [comment]
Looks like this is the behaviour in Node too and according to the docs for [url.format](https://nodejs.org/api/url.html#url_url_format_urlobject) `search` takes precedence over `query`.

**Comment by ljharb** [comment]
Whatever node does, this module should do. I'd suggest filing a bug on node itself if you find its behavior surprising.
