### ISSUE TITLE
Sometimes punycode is failing when it's bundled with bundlers, the result is that punnycode object is empty.

### ISSUE THREAD

**Issue by h3xxx** [defunctzombie/node-url#31]
Sometimes punycode is failing when it's bundled with bundlers (browserify, webpack), the result is that punnycode object is empty. It's causing: 
`Uncaught TypeError: punycode.toASCII is not a function` in node-url.

My suggestion it to add a condition near line 295 in url.js:

```javascript
if (typeof punycode.toASCII == 'function')
    this.hostname = punycode.toASCII(this.hostname);
````

**Comment by manuelnaranjo** [comment]
Seems this branch has the issue solved by just moving out of punycode:

https://github.com/adampash/node-url/commit/01ff22ebee841a0053330d45f221371b41effbbf

**Comment by h3xxx** [comment]
@manuelnaranjo thanks for info, I'm closing the issue.
