### ISSUE TITLE
Why not toString?

### ISSUE THREAD

**Issue by gwiron** [defunctzombie/node-url#38]
Many methods written in the document, why not here?

The reference in the document is URL, and why is it actually Url?
```
const { Url } = require ('url')
```

**Comment by gwiron** [comment]
This URL non node URL?

**Comment by Setitch** [comment]
The name 'url' is builtin module for node, this trash module here breaks usage of that module. For example with browserity - you cannot work properly with URL module from node, as this trash takes is place.

**Comment by ljharb** [comment]
This is a browser-compatible replacement for node's core `url` module.

Anything it supports and we don't, is a bug. Anything it doesn't support, we won't be adding, and you should file an issue on node itself requesting that support.
