### ISSUE TITLE
Add Typescript types

### ISSUE THREAD

**Issue by yordis** [defunctzombie/node-url#41]

**Comment by prmichaelsen** [comment]
Surprising such a popular lib doesn't have Typescript types

**Comment by prmichaelsen** [comment]
My recommendation would be to not use this library and instead install `npm install     ------- --save-dev @types/node` and use the built-in node url.

**Comment by shepmaster** [comment]
As obliquely alluded to above, you can use this library *with* the types from the `@types/node` package:

```js
  "dependencies": {
    "url": "^0.11.0"
  },
  "devDependencies": {
    "@types/node": "^11.9.5"
  }
```

**Comment by prmichaelsen** [comment]
@shepmaster as far as I can tell, this project has not been updated for 3 years. You are likely better off using built in the node functions.

**Comment by shepmaster** [comment]
> using the built in node functions.

@prmichaelsen How is it possible to use the Node functions in a web browser context? I use this package to have URL parsing and formatting tools in the browser.

**Comment by prmichaelsen** [comment]
In that case, carry on

**Comment by yordis** [comment]
I agree with @prmichaelsen people should use built-in Node `url` package.
