### ISSUE TITLE
substr(-1) not supported in all browsers

### ISSUE THREAD

**Issue by tommymessbauer** [defunctzombie/node-url#6]
Older browsers do not support substr(-1) and this makes url unusable in older browsers.  I have been using this polyfill in my libraries to get around it but IMO, we should fix this in the browserify dep.  

https://github.com/tommymessbauer/substr-polyfill/blob/master/index.js

The core node.js team rejected the change on the grounds that node is not meant to support browsers.
https://github.com/joyent/node/issues/6745

I have a PR coming...

**Comment by jhiesey** [comment]
What's the status on this? @defunctzombie, are you strongly opposed to adding compatibility code in here? I think I can come up with a cleaner fix than the proposed PR (#7)

I'd like to use `url.resolve` in [stream-http](https://github.com/jhiesey/stream-http), but I'm also hoping to keep IE8 support without polyfills.

As far as I can tell, fixing this and replacing `Object.keys` with https://www.npmjs.com/package/object-keys would fix this module.

**Comment by defunctzombie** [comment]
As my comment above says, I don't think it is worth the effort when polyfills will do. At this point these browsers are "beyond" legacy and not worth the time and hacks in supporting.
