### ISSUE TITLE
version 0.11.1 has bug, show querystring.stringify is not a function

### ISSUE THREAD

**Issue by hoticer** [defunctzombie/node-url#64]
when item start show in console:
querystring.stringify is not a function
    at push../node_modules/url/url.js.Url.format
![image](https://github.com/defunctzombie/node-url/assets/10001817/591fb1e6-1c8e-43d1-86dc-fb2597ced009)
![image](https://github.com/defunctzombie/node-url/assets/10001817/44e60ec7-e345-4be9-9e7c-364b55337567)
![image](https://github.com/defunctzombie/node-url/assets/10001817/30461c61-63d0-4967-a99f-6aae7f4914db)

**Comment by ljharb** [comment]
This seems like something in your build process - that `querystring` variable is the `qs` package, which has `formats`, `parse`, and `stringify`, and it's definitely not an image.

**Comment by ljharb** [comment]
I'm going to close this, but happy to keep discussing.
