### ISSUE TITLE
npm install fails when installing browserify

### ISSUE THREAD

**Issue by jakkirhussain** [defunctzombie/node-url#71]
Failed in branch Build Upstream
npm ERR! code ETARGET
npm ERR! notarget No matching version found for url@0.11.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by ljharb** [comment]
https://unpkg.com/browse/url@0.11.4/ definitely exists - that suggests that your private registry isn't properly syncing with the public registry.
