### ISSUE TITLE
punycode deprecation

### ISSUE THREAD

**Issue by jmims-magnusdigital** [defunctzombie/node-url#74]
In newer versions of node, punycode triggers a deprecation warning

```
(node:91080) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
```

**Comment by ljharb** [comment]
We’re already using the userland module. Are you sure this warning comes from this package?

**Comment by jmims-magnusdigital** [comment]
I could have probably read the dependency warning wrong, or am at the wrong repository lol I'll double check

**Comment by jmims-magnusdigital** [comment]
dependency chart*

**Comment by mgara** [comment]
Hi there, I'm worried that this is causing the issue unless there is something else : 
this is the result of `npm ls punycode`
```
foo@0.0.0 /Users/myuser/work/monorepo
└─┬ foo/scheduler@1.0.0 -> ./apps/scheduler
  ├─┬ foo/backend-services@1.0.0 -> ./libs/backend-services
  │ └─┬ url@0.11.4
  │   └── punycode@1.4.1
  ├─┬ @kubernetes/client-node@0.22.3
  │ └─┬ request@2.88.2
  │   └─┬ tough-cookie@2.5.0
  │     └── punycode@2.3.1
  └─┬ eslint@9.17.0
    └─┬ ajv@6.12.6
      └─┬ uri-js@4.4.1
        └── punycode@2.3.1 deduped
```
I don't think the deprecation warning coming from the `punycode 2.3.1` ... :/

**Comment by ljharb** [comment]
The warning is coming from something that *doesnt* show up in the npm graph, that’s the problem. Anything directly using the punycode package is fine.

**Comment by mgara** [comment]
apparently it's coming from `whatwg-url`

**Comment by ljharb** [comment]
Looks like it might be deeper than that: https://github.com/jsdom/whatwg-url/issues/279 https://github.com/jsdom/whatwg-url/issues/278#issuecomment-2374180860

Either way though, I'll close it, since it's got nothing to do with this project.
